replicaCount: 1

timezone: "Europe/Paris"

image:
  repository: ghcr.io/blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: "0.14.1"
  flavor: "" # nvidia => "tensorrt"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  host: ""
  tls: ""

serviceAccount:
  create: false

coral:
  enabled: false
  hostPath: /dev/bus/usb
gpu:
  nvidia: 0

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 1Gi
  #   nvidia.com/gpu: 1
  # requests:
  #   cpu: 500m
  #   memory: 500Mi
  #   nvidia.com/gpu: 1

securityContext: {}
  # privileged: true # for usb coral

shmSize: 1Gi

tmpfs:
  enabled: true
  sizeLimit: 1Gi

persistence:
  config:
    enabled: false
    accessMode: ReadWriteOnce
    size: 100Mi
    storageClass: ""
    existingClaim: false
  media:
    enabled: false
    hostPath: ""
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: ""
    existingClaim: false

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /api/version
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
startupProbe: 
  httpGet:
    path: /api/version
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 30
  failureThreshold: 7
