{{- if .Values.postgresql.enabled }}
apiVersion: v1
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password.admin | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: kubernetes.io/basic-auth
{{- end }}