{{- if .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-cnpg
spec:
  instances: 1
  postgresql:
    parameters:
      timezone: "Europe/Paris"
  bootstrap:
    initdb:
      database: {{ .Release.Name }}
      owner: {{ .Values.postgresql.auth.username }}
      secret:
        name: {{ .Release.Name }}-db-secret
      postInitSQL:
        - CREATE USER radarr WITH PASSWORD '{{ .Values.postgresql.auth.password.radarr }}'
        - CREATE DATABASE radarr_main OWNER radarr
        - CREATE DATABASE radarr_log OWNER radarr
        - CREATE USER sonarr WITH PASSWORD '{{ .Values.postgresql.auth.password.sonarr }}'
        - CREATE DATABASE sonarr_main OWNER sonarr
        - CREATE DATABASE sonarr_log OWNER sonarr
        - CREATE USER prowlarr WITH PASSWORD '{{ .Values.postgresql.auth.password.prowlarr }}'
        - CREATE DATABASE prowlarr_main OWNER prowlarr
        - CREATE DATABASE prowlarr_log OWNER prowlarr
        - CREATE USER lidarr WITH PASSWORD '{{ .Values.postgresql.auth.password.lidarr }}'
        - CREATE DATABASE lidarr_main OWNER lidarr
        - CREATE DATABASE lidarr_log OWNER lidarr
  monitoring:
    enablePodMonitor: true
  storage:
    size: 1Gi
    storageClass: {{ .Values.postgresql.storageClass }}
{{- end }}