{{- if .Values.global.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.rbac.clusterRoleName }}
  labels:
    {{ include "commons.labels" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .Values.global.rbac.clusterRoleName) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.global.rbac.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.rbac.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
