{{- if .Values.global.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.rbac.serviceAccountName }}
  labels:
    {{ include "commons.labels" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .Values.global.rbac.serviceAccountName) | nindent 4 }}
secrets:
  - name: {{ .Values.global.rbac.serviceAccountName }}-secret
{{- end }}
