{{- if and .Values.lldap.enabled .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-lldap-cnpg
  labels:
    app.kubernetes.io/component: lldap
spec:
  instances: 1
  postgresql:
    parameters:
      timezone: "Europe/Paris"
  bootstrap:
    initdb:
      database: lldap
      owner: {{ .Values.postgresql.lldap.user }}
      secret:
        name: {{ .Release.Name }}-lldap-cnpg-secret
  monitoring:
    enablePodMonitor: true
  storage:
    size: 1Gi
    storageClass: {{ .Values.postgresql.storageClass }}
{{- end }}