{{- if .Values.lldap.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authelia.fullname" . }}-lldap
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
    app.kubernetes.io/component: lldap
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "authelia.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: lldap
  template:
    metadata:
      labels:
        {{- include "authelia.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: lldap
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.lldap.image.repository }}:{{ .Values.lldap.image.tag }}{{- with .Values.lldap.image.flavor }}-{{ . }}{{- end }}"
        env:
          - name: TZ
            value: "{{ .Values.timezone }}"
          - name: LLDAP_JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "authelia.fullname" . }}-lldap
                key: lldap-jwt-secret
          - name: LLDAP_LDAP_BASE_DN
            valueFrom:
              secretKeyRef:
                name: {{ include "authelia.fullname" . }}-lldap
                key: base-dn
          - name: LLDAP_LDAP_USER_DN
            value: "admin"
          - name: LLDAP_KEY_SEED
            valueFrom:
              secretKeyRef:
                name: {{ include "authelia.fullname" . }}-lldap
                key: lldap-key-seed
          - name: LLDAP_LDAP_USER_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "authelia.fullname" . }}-lldap
                key: lldap-ldap-user-pass
          - name: LLDAP_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "authelia.fullname" . }}-lldap
                key: lldap-database-url
        ports:
          - containerPort: 3890
            name: lldap
          - containerPort: 17170
            name: http
        livenessProbe:
          httpGet:
            path: /
            port: 17170
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 17170
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
          - mountPath: /data
            name: lldap-data
      volumes:
        - name: lldap-data
          {{- if .Values.lldap.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.lldap.persistence.existingClaim }}{{ .Values.lldap.persistence.existingClaim }}{{- else }}lldap-pvc{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
