{{- if .Values.lldap.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secrets-lldap
data:
  lldap-jwt-secret: {{ .Values.lldap.jwtSecret | b64enc | quote }}
  lldap-key-seed: {{ .Values.lldap.keySeed | b64enc | quote }}
  base-dn: {{ .Values.lldap.baseDn | b64enc | quote }}
  lldap-ldap-user-pass: {{ .Values.lldap.password | b64enc | quote }}
  lldap-database-url: {{ printf "postgres://%s:%s@%s-lldap-cnpg-rw:5432/lldap" .Values.postgresql.lldap.user .Values.postgresql.lldap.password .Release.Name | b64enc | quote }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
data:
  username: {{ .Values.postgresql.lldap.user | b64enc }}
  password: {{ .Values.postgresql.lldap.password | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-lldap-cnpg-secret
  labels:
    app.kubernetes.io/component: lldap
type: kubernetes.io/basic-auth
{{- end }}
{{- end }}