{{- if .Values.postgresql.enabled }}
apiVersion: v1
data:
  username: {{ .Values.postgresql.user | b64enc }}
  password: {{ .Values.postgresql.password | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: kubernetes.io/basic-auth
{{- end }}