{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  annotations:
    {{- with .Values.ingress.annotations }}
    annotations:
      {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: tls-vaultwarden
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vaultwarden.fullname" . }}
                port:
                  name: http
{{- end }}
