apiVersion: v1
kind: Service
metadata:
  name: {{ template "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.service.loadBalancerIP }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ . }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    {{- include "vaultwarden.selectorLabels" . | nindent 8 }}
