{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jellyfin.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.tls }}"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: tls-jellyfin
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" . }}
                port:
                  name: http
{{- end }}
