apiVersion: v1
kind: Service
metadata:
  name: {{ template "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
  - name: http
    protocol: TCP
    port: 8096
    targetPort: 8096
  - name: https
    protocol: TCP
    port: 8920
    targetPort: 8920
  {{- if .Values.enableDLNA }}
  - name: dlna-1900
    protocol: UDP
    port: 1900
    targetPort: 1900
  - name: dlna-7359
    protocol: UDP
    port: 7359
    targetPort: 7359
  {{- end }}
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 8 }}
