
{{- if .Values.clamav.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-clamav
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: clamav
spec:
  type: {{ .Values.clamav.service.type }}
  ports:
    - name: "clamav"
      port: 3310
      targetPort: "clamav"
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: clamav
{{- end }}
