{{- if .Values.sonarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.fullname" . }}-sonarr
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: sonarr
spec:
  type: {{ .Values.sonarr.service.type }}
  ports:
    - port: {{ .Values.sonarr.service.port }}
      targetPort: sonarr
      protocol: TCP
      name: sonarr
  selector:
    {{- include "servarr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sonarr
{{- end }}
