{{- if .Values.sonarr.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: {{ include "servarr.fullname" . }}-sonarr
  {{- with .Values.sonarr.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
 tls:
   - hosts:
       - {{ .Values.sonarr.ingress.host }}
     secretName: tls-sonarr
 rules:
   - host: {{ .Values.sonarr.ingress.host }}
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: {{ include "servarr.fullname" . }}-sonarr
               port:
                 name: sonarr
{{- end }}