replicaCount: 1

image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
  tag: "2.0.22"

timezone: "Europe/Paris"

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  existingClaim: false
  storageClass: ""

config: |
  listener 1883
  listener 9001
  protocol websockets
  allow_anonymous true
  # persistence true
  # persistence_location /mosquitto/data
  # autosave_interval 1800
  # include_dir /mosquitto/configinc
  # log_dest file /mosquitto/log/mosquitto.log

service:
  type: ClusterIP
  port: 1883

serviceAccount:
  create: false

# authentication:
#   user: mosquitto
#   password: changeme
