replicaCount: 1

image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
  tag: "2.0.20"

timezone: "Europe/Paris"

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  existingClaim: false
  storageClass: ""

service:
  type: ClusterIP
  port: 1883

serviceAccount:
  create: false

user: mosquitto
password: changeme

addons:
  zigbee2mqtt:
    enabled: false
    replicaCount: 1
    homeassistant: false
    zigbee: /dev/ttyACM0
    image:
      repository: koenkk/zigbee2mqtt
      tag: "1.42.0"
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 1Gi
      existingClaim: false
      storageClass: ""
    service:
      type: ClusterIP
      port: 8080