replicaCount: 1

image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
  tag: "2.0.21"

timezone: "Europe/Paris"

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  existingClaim: false
  storageClass: ""

config: |
  listener 1883
  listener 9001
  protocol websockets
  allow_anonymous true
  # persistence true
  # persistence_location /mosquitto/data
  # autosave_interval 1800
  # include_dir /mosquitto/configinc
  # log_dest file /mosquitto/log/mosquitto.log

service:
  type: ClusterIP
  port: 1883

serviceAccount:
  create: false

# authentication:
#   user: mosquitto
#   password: changeme

addons:
  zigbee2mqtt:
    enabled: false
    replicaCount: 1
    homeassistant: false
    path: /dev/ttyACM0
    port: /dev/ttyACM0
    adapter: deconz
    image:
      repository: koenkk/zigbee2mqtt
      tag: "2.1.3"
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 1Gi
      existingClaim: false
      storageClass: ""
    service:
      type: ClusterIP
      port: 8080
    resources:
      requests:
        memory: 600Mi
        cpu: 200m
      limits:
        memory: 600Mi
        cpu: 200m