{{- if .Values.radarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.fullname" . }}-radarr
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: radarr
spec:
  type: {{ .Values.radarr.service.type }}
  ports:
    - port: {{ .Values.radarr.service.port }}
      targetPort: radarr
      protocol: TCP
      name: radarr
  selector:
    {{- include "servarr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: radarr
{{- end }}
