{{- if and .Values.radarr.enabled .Values.radarr.persistence.enabled  }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-pvc-config
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: radarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.radarr.persistence.size | quote }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}