{{- if .Values.whisper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "assist.fullname" . }}-whisper
  labels:
    {{- include "assist.labels" . | nindent 4 }}
    app.kubernetes.io/component: whisper
spec:
  type: {{ .Values.whisper.service.type }}
  ports:
    - port: {{ .Values.whisper.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "assist.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: whisper
{{- end }}
