{{- if .Values.codeserver.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: {{ include "servarr.fullname" . }}-codeserver
 annotations:
   cert-manager.io/cluster-issuer: "{{ .Values.codeserver.ingress.tls }}"
spec:
 tls:
   - hosts:
       - {{ .Values.codeserver.ingress.host }}
     secretName: tls-codeserver
 rules:
   - host: {{ .Values.codeserver.ingress.host }}
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: {{ include "servarr.fullname" . }}-codeserver
               port:
                 name: codeserver
{{- end }}