{{- if and .Values.addons.codeserver.enabled .Values.addons.codeserver.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: codeserver-pvc-config
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: codeserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.addons.codeserver.persistence.size | quote }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}