{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- range $components }}
{{- $component := . }}
{{- range $component.deployment.volumes }}
{{- $volume := . }}
{{- $configMap := $volume.configMap }}
{{- if and $configMap (not $configMap.useExisting) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default $volume.name $configMap.name) "component" $component) }}
  labels:
    {{ include "commons.labels" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default $volume.name $configMap.name) "component" $component) | nindent 4 }}
data:
  {{- range $filename, $content := $configMap.spec.data }}
  {{ $filename }}: |-
  {{ $content | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
