{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- range $components }}
{{- $component := . }}
{{- with $component.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (get $component.configMap.name "name" | default "configmap") "component" $component) }}
  labels:
    {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (get $component.configMap.name "name" | default "configmap") "component" $component) | nindent 4 }}
data:
  {{- range $filename, $content := .data }}
  {{ $filename }}: |-
  {{ $content | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
