{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- range $components }}
{{- $component := . }}
{{- with $component.cronjob }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .name "component" $component) }}
spec:
  schedule: {{ .schedule | quote }}
  {{- with .concurrencyPolicy}}
  concurrencyPolicy: {{ . | quote }}
  {{- end }}
  {{- with .concurrencyPolicy}}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  successfulJobsHistoryLimit: {{ default 5 .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 5 .failedJobsHistoryLimit }}
  {{- with .suspend}}
  suspend: {{ . }}   
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ default "Never" .restartPolicy }}
          {{- if $.Values.global.rbac.enabled }}
          serviceAccountName: {{ $.Values.global.rbac.serviceAccountName }}
          automountServiceAccountToken: true
          {{- end }}
          {{- $sc := .securityContext | default (dict) }}
          {{- $gsc := $.Values.global.securityContext | default (dict) }}
          securityContext:
            {{- if hasKey $sc "runAsUser" }}
            runAsUser: {{ $sc.runAsUser }}
            {{- else if hasKey $gsc "runAsUser" }}
            runAsUser: {{ $gsc.runAsUser }}
            {{- end }}
            {{- if hasKey $sc "runAsGroup" }}
            runAsGroup: {{ $sc.runAsGroup }}
            {{- else if hasKey $gsc "runAsGroup" }}
            runAsGroup: {{ $gsc.runAsGroup }}
            {{- end }}
            {{- if hasKey $sc "fsGroup" }}
            fsGroup: {{ $sc.fsGroup }}
            {{- else if hasKey $gsc "fsGroup" }}
            fsGroup: {{ $gsc.fsGroup }}
            {{- end }}
          {{- with .hostNetwork }}
          hostNetwork: {{ . }}
          {{- end }}
          {{- with .initContainers }}
          initContainers:
            {{- range . }}
            - name: {{ .name | default $component.name }}
              {{- with .securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: {{ .image.repository }}:{{ .image.tag | default "latest"  }}
              {{- with .command }}
              command:
                {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with .args }}
              args:
                {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with .env }}
              env:
                - name: TZ
                  value: {{ $.Values.global.timezone | quote }}
                {{- range . }}
                - name: {{ .name }}
                  {{- with .value }}
                  value: {{ include "commons.getValue" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "value" .) | quote }}
                  {{- end }}
                  {{- with .valueFrom }}
                  valueFrom:
                    {{- if .secretKeyRef }}
                    secretKeyRef:
                      name: {{ include "commons.getValue" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "value" .secretKeyRef.name) }}
                      key: {{ .secretKeyRef.key }}
                    {{- else }}
                    {{- toYaml . | nindent 20 }}
                    {{- end }}
                  {{- end }}
                {{- end }}
              {{- end }}
              {{- with .volumeMounts }}
              volumeMounts:
                {{- range . }}
                - name: {{ .name }}
                  mountPath: {{ .mountPath }}
                  {{- with .subPath }}
                  subPath: {{ . }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          containers:
            - name: {{ default $component.name .name }}
              image: {{ .image.repository }}:{{ .image.tag | default "latest" }}
              {{- with .command }}
              command:
                {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with .args }}
              args:
                {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with .securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: TZ
                  value: {{ $.Values.global.timezone | quote }}
                {{- range .env }}
                - name: {{ .name }}
                  {{- with .value }}
                  value: {{ include "commons.getValue" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "value" .) | quote }}
                  {{- end }}
                  {{- with .valueFrom }}
                  valueFrom:
                    {{- if .secretKeyRef }}
                    secretKeyRef:
                      name: {{ include "commons.getValue" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "value" .secretKeyRef.name) }}
                      key: {{ .secretKeyRef.key }}
                    {{- else }}
                    {{- toYaml . | nindent 20 }}
                    {{- end }}
                  {{- end }}
                {{- end }}
              {{- with .lifecycle }}
              lifecycle:
              {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .volumeMounts }}
              volumeMounts:
                {{- range . }}
                - name: {{ .name }}
                  mountPath: {{ .mountPath }}
                  {{- with .subPath }}
                  subPath: {{ . }}
                  {{- end }}
                {{- end }}
              {{- end }}
              

              {{- with .resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            {{ include "containers.sidecars" (dict "component" $component "Values" $.Values) | nindent 8 }}
          {{- with .volumes }}
          volumes:
            {{- range . }}
            {{- if .configMap }}
            - name: {{ .name }}
              configMap:
                {{- if .configMap.useExisting }}
                name: {{ include "commons.getValue" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "value" .configMap.name) }}
                {{- else }}
                name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default .name .configMap.name) "component" $component) }}
                {{- end }}
                {{- with .configMap.readOnly }}
                readOnly: {{ . }}
                {{- end }}
            {{- else if .pvc }}
            - name: {{ .name }}
              persistentVolumeClaim:
                {{- if .pvc.useExisting }}
                claimName: {{ include "commons.getValue" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "value" .pvc.name) }}
                {{- else }}
                claimName: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default .name .pvc.name) "component" $component) }}
                {{- end }}
                {{- with .pvc.readOnly }}
                readOnly: {{ . }}
                {{- end }}
            {{- else }}
            - {{ toYaml . | nindent 14 | trim }}
              {{- end }}
            {{- end }}
          {{- end }}
---
{{- end }}
{{- end }}