{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- range $components }}
{{- $component := . }}
{{- range $component.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
{{- $volume := . }}
{{- $pvc := $volume.pvc }}
{{- if $pvc }}
TATA: 4
{{- with $pvc.spec }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default $volume.name $pvc.name) "component" $component) }}
  labels:
    {{ include "commons.labels" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default $volume.name $pvc.name) "component" $component) | nindent 4 }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .storage | default $.Values.global.pvc.storage.size }}
  storageClassName: {{ .storageClassName | default $.Values.global.pvc.storage.storageClassName }}
  {{- if .volumeMode }}
  volumeMode: {{ .volumeMode }}
  {{- end }}
  {{- if .selector }}
  selector:
    {{- toYaml .selector | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
