{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- range $components }}
{{- $component := . }}
{{- range $component.deployment.volumes }}
{{- $volume := . }}
{{- $pvc := $volume.pvc }}
{{- if and $pvc (not $pvc.useExisting) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default $volume.name $pvc.name) "component" $component) }}
  labels:
    {{ include "commons.labels" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default $volume.name $pvc.name) "component" $component) | nindent 4 }}
spec:
  accessModes:
    - {{ get (get $pvc "spec" | default dict) "accessMode" | default $.Values.global.pvc.storage.accessMode }}
  resources:
    requests:
      storage: {{ get (get $pvc "spec" | default dict) "storage" | default $.Values.global.pvc.storage.size }}
  storageClassName: {{ get (get $pvc "spec" | default dict) "storageClassName" | default $.Values.global.pvc.storage.storageClassName }}
  {{- if get (get $pvc "spec" | default dict) "volumeMode" }}
  volumeMode: {{ $pvc.spec.volumeMode }}
  {{- end }}
  {{- if get (get $pvc "spec" | default dict) "selector" }}
  selector:
    {{- toYaml $pvc.spec.selector | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
