{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- range $components }}
{{- $component := . }}
{{- range $component.secrets }}
apiVersion: v1
data:
{{- range $name, $content := .data }}
  {{ $name }}: {{ $content | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .name "component" $component) }}
type: {{ default "Opaque" .type }}
{{- end }}
{{- end }}