{{- if .Values.global.rbac.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.global.rbac.serviceAccountName }}-secret
  labels:
    {{ include "commons.labels" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .Values.global.rbac.serviceAccountName) | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.global.rbac.serviceAccountName }}
{{- end }}