{{- if .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-cnpg
spec:
  instances: 1
  postgresql:
    parameters:
      timezone: "Europe/Paris"
  bootstrap:
    initdb:
      database: authelia
      owner: {{ .Values.postgresql.authelia.user }}
      secret:
        name: {{ .Release.Name }}-db-secret
  monitoring:
    enablePodMonitor: true
  storage:
    size: 1Gi
    storageClass: {{ .Values.postgresql.storageClass }}
{{- end }}