apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authelia.fullname" . }}
data:
  configuration.yaml : |
    theme: {{ .Values.config.theme }}
    default_2fa_method: {{ .Values.config.default_2fa_method }}

    {{- with .Values.config.server }}
    server:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.log }}
    log:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.identity_validation }}
    identity_validation:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.webauthn }}
    webauthn:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.totp }}
    totp:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    ntp:
      address: "udp://time.cloudflare.com:123"
      version: 3
      max_desync: "3s"
      disable_startup_check: false
      disable_failure: false
    
    {{- if .Values.lldap.enabled }}
    authentication_backend:
      {{- with .Values.config.password_reset }}
      password_reset:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      ldap:
        implementation: "custom"
        address: ldap://{{ include "authelia.fullname" . }}-lldap:3890
        timeout: "5s"
        start_tls: false
        additional_users_dn: "ou=people"
        users_filter: "(&({username_attribute}={input})(objectClass=person))"
        additional_groups_dn: "ou=groups"
        groups_filter: "(member={dn})"
        attributes: 
          group_name: cn
          mail: mail
          display_name: displayName
        base_dn: '{{ .Values.lldap.baseDn }}'
        user: 'uid=admin,ou=people,{{ .Values.lldap.baseDn }}'
    {{- end }}

    {{- with .Values.config.password_policy }}
    password_policy:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    session:
      name: "authelia_session"
      same_site: "lax"
      inactivity: "5m"
      expiration: "1h"
      remember_me: "1M"
      cookies:
        - domain: '{{ .Values.ingress.domain }}'
          authelia_url: 'https://{{ .Values.ingress.host }}'
          name: 'authelia_session' 
          same_site: 'lax'
          inactivity: '5m'
          expiration: '1h'
          remember_me: '1d'
      redis:
        host: {{ .Release.Name }}-redis-master
        port: 6379
        database_index: 0
        minimum_idle_connections: 0
    
    {{- with .Values.config.regulation }}
    regulation:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- if .Values.postgresql.enabled }}
    storage:
      postgres:
        address: {{ .Release.Name }}-cnpg-rw
        timeout: "5s"
        database: "authelia"
        schema: "public"
        username: {{ .Values.postgresql.authelia.user }}
    {{- end }}

    {{- with .Values.config.access_control }}
    access_control:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    notifier:
      smtp:
        address: "{{ .Values.smtp.address }}"
        username: "{{ .Values.smtp.username }}"
        sender: "{{ .Values.smtp.sender }}"

    {{- with .Values.config.identity_providers }}
    identity_providers:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.telemetry }}
    telemetry:
      {{- toYaml . | nindent 6 }}
    {{- end }}