apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authelia.fullname" . }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
    app.kubernetes.io/component: authelia
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "authelia.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: authelia
  template:
    metadata:
      labels:
        {{- include "authelia.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: authelia
    spec:
      securityContext:
        fsGroup: 1000
      hostNetwork: false
      hostPID: false
      hostIPC: false
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: AUTHELIA_SERVER_DISABLE_HEALTHCHECK
              value: "true"
            - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
              value: "/secrets/JWT_SECRET"
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: "/secrets/SESSION_SECRET"
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
              value: "/secrets/STORAGE_ENCRYPTION_KEY"
            - name: AUTHELIA_SESSION_REDIS_PASSWORD_FILE
              value: "/secrets/REDIS_PASSWORD"
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
              value: "/secrets/LDAP_PASSWORD"
            - name: AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
              value: "/secrets/SMTP_PASSWORD"
            - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
              value: "/secrets/STORAGE_PASSWORD"
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 9091
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 9091
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          volumeMounts:
            - mountPath: /config/configuration.yml
              name: config
              subPath: configuration.yaml
            - mountPath: /secrets/JWT_SECRET
              name: secrets
              subPath: jwt-secret
            - mountPath: /secrets/SESSION_SECRET
              name: secrets
              subPath: session-secret
            - mountPath: /secrets/STORAGE_ENCRYPTION_KEY
              name: secrets
              subPath: storage-encryption-key
            - mountPath: /secrets/REDIS_PASSWORD
              name: secrets
              subPath: redis-secret
            - mountPath: /secrets/LDAP_PASSWORD
              name: secrets
              subPath: ldap-secret
            - mountPath: /secrets/SMTP_PASSWORD
              name: secrets
              subPath: smtp-secret
            - mountPath: /secrets/STORAGE_PASSWORD
              name: secrets
              subPath: postgres-secret
      volumes:
        - name: config
          configMap:
            name: {{ include "authelia.fullname" . }}
        - name: secrets
          secret:
            secretName: {{ include "authelia.fullname" . }}