apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-authelia
  namespace: traefik
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://{{ template "authelia.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local/api/authz/forward-auth
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
      - Remote-Name