apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "authelia.fullname" . }}
data:
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  session-secret: {{ .Values.sessionSecret | b64enc | quote }}
  storage-encryption-key: {{ .Values.storageEncryptionKey | b64enc | quote }}
  redis-secret: {{ .Values.redis.global.redis.password | b64enc | quote }}
  ldap-secret: {{ .Values.lldap.password | b64enc | quote }}
  smtp-secret: {{ .Values.smtp.password | b64enc | quote }}
  postgres-secret: {{ .Values.postgresql.authelia.password | b64enc | quote }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
data:
  username: {{ .Values.postgresql.authelia.user | b64enc }}
  password: {{ .Values.postgresql.authelia.password | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: kubernetes.io/basic-auth
{{- end }}