apiVersion: v1
kind: Service
metadata:
  name: {{ template "authelia.fullname" . }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
    app.kubernetes.io/component: authelia
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
  selector:
    {{- include "authelia.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: authelia
