{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- $raw := .Values.addons | default dict }}
{{- $_ := set $raw "name" "postgres" }}
{{- $components = append $components $raw }}
{{- range $components }}
{{- $component := . }}
{{- with $component.postgres }}
{{- if .enabled }}
{{- with .init }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .name "component" $component) }}-configmap
data:
  init.sql: |
    echo "toto"
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
