{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- range $components }}
{{- $component := . }}
{{- with $component.postgres }}
{{- range .init }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ . }}
data:
  init.sql: |
---
{{- end }}
{{- end }}
{{- end }}
