{{- if .Values.prowlarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servarr.fullname" . }}-prowlarr
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: prowlarr
spec:
  replicas: {{ .Values.prowlarr.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "servarr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prowlarr
  template:
    metadata:
      labels:
        {{- include "servarr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prowlarr
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ include "servarr.serviceAccountName" . }}
      {{- if .Values.postgresql.enabled }}
      initContainers:
        - name: check-db-ready
          image: bitnami/postgresql:16
          command: ['sh', '-c', 'until pg_isready -d prowlarr_main -U prowlarr -h {{ .Release.Name }}-cnpg-rw; do echo waiting for database; sleep 2; done;']
        - name: init-config
          image: busybox
          command: ['sh', '/tmp/init.sh']
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/config.xml
              subPath: config.xml
            - name: script-volume
              mountPath: /tmp/init.sh
              subPath: init.sh
            - name: prowlarr-config
              mountPath: /config
      {{- end }}
      containers:
        - name: prowlarr
          image: "{{ .Values.prowlarr.image.repository }}:{{ .Values.prowlarr.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: prowlarr
              containerPort: {{ .Values.prowlarr.port }}
              protocol: TCP
          env:
            {{- range .Values.prowlarr.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.prowlarr.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.prowlarr.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
      volumes:
        - name: prowlarr-config
          {{- if .Values.prowlarr.persistence.enabled }}
          persistentVolumeClaim:
            claimName: prowlarr-pvc-config
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.postgresql.enabled }}
        - name: config-volume
          configMap:
            name: config-prowlarr
        - name: script-volume
          configMap:
            name: servarr-script
        {{- end }}
      {{- with .Values.prowlarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prowlarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prowlarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
