apiVersion: v1
kind: ConfigMap
metadata:
  name: config-prowlarr
data:
  config.xml: |
    <Config>
        <BindAddress>*</BindAddress>
        <Port>{{ .Values.prowlarr.service.port }}</Port>
        <SslPort>6969</SslPort>
        <EnableSsl>False</EnableSsl>
        <LaunchBrowser>True</LaunchBrowser>
        <ApiKey>87cb60c12a1a43cab8c679566e78d48c</ApiKey>
        <AuthenticationMethod>None</AuthenticationMethod>
        <AuthenticationRequired>Enabled</AuthenticationRequired>
        <Branch>master</Branch>
        <LogLevel>debug</LogLevel>
        <SslCertPath />
        <SslCertPassword />
        <UrlBase />
        <InstanceName>Prowlarr</InstanceName>
        <UpdateMechanism>Docker</UpdateMechanism>
        <PostgresUser>prowlarr</PostgresUser>
        <PostgresPassword>{{ .Values.postgresql.auth.password.prowlarr }}</PostgresPassword>
        <PostgresPort>5432</PostgresPort>
        <PostgresHost>{{ .Release.Name }}-cnpg-rw</PostgresHost>
        <PostgresMainDb>prowlarr_main</PostgresMainDb>
        <PostgresLogDb>prowlarr_log</PostgresLogDb>
    </Config>