{{- if .Values.prowlarr.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: {{ include "servarr.fullname" . }}-prowlarr
  {{- with .Values.prowlarr.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
 tls:
   - hosts:
       - {{ .Values.prowlarr.ingress.host }}
     secretName: tls-prowlarr
 rules:
   - host: {{ .Values.prowlarr.ingress.host }}
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: {{ include "servarr.fullname" . }}-prowlarr
               port:
                 name: prowlarr
{{- end }}