apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}-script-init
data:
  init.sh: |
    #!/bin/sh

    echo "Début de l'initialisation de mqtt"

    echo "mkdir /mosquitto/config"
    mkdir /mosquitto/config
    echo "mkdir /mosquitto/configinc"
    mkdir /mosquitto/configinc

    echo "password_file /mosquitto/configinc/passwordfile" > /mosquitto/configinc/passwordconfig.conf

    echo "Fin de l'initialisation de mqtt"