apiVersion: v1
kind: Service
metadata:
  name: {{ template "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mqtt
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: mqtt
    - name: mqtt-ws
      port: 9001
      protocol: TCP
      targetPort: mqtt-ws
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt
