apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}-script-init
data:
  init.sh: |
    #!/bin/sh

    echo "Début de l'initialisation de mqtt"

    echo "mkdir /mosquitto/config"
    if [ ! -f "/mosquitto/config" ]; then
      mkdir /mosquitto/config
    fi
    echo "mkdir /mosquitto/configinc"
    if [ ! -f "/mosquitto/configinc" ]; then
      mkdir /mosquitto/configinc
      echo "password_file /mosquitto/configinc/passwordfile" > /mosquitto/configinc/passwordconfig.conf
    else
      rm -f /mosquitto/configinc/passwordfile
    fi

    chown -R 1883:1883 /mosquitto

    echo "Fin de l'initialisation de mqtt"