{{- if .Values.addons.zigbee2mqtt.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}-zigbee2mqtt
data:
  configuration.yaml: |
    # Home Assistant integration (MQTT discovery)
    homeassistant:
      enabled: {{ .Values.addons.zigbee2mqtt.homeassistant }}
      {{- if .Values.addons.zigbee2mqtt.homeassistant }}
      status: 'hass/status'
      {{- end }}

    frontend:
      enabled: true
      port: {{ .Values.addons.zigbee2mqtt.service.port }}

    # allow new devices to join
    permit_join: true

    advanced:
      homeassistant_legacy_entity_attributes: false
      homeassistant_legacy_triggers: false
      legacy_api: false
      legacy_availability_payload: false
    device_options:
      legacy: false

    # MQTT settings
    mqtt:
      # MQTT base topic for zigbee2mqtt MQTT messages
      base_topic: zigbee2mqtt
      # MQTT server URL
      server: 'mqtt://{{ template "mosquitto.fullname" . }}'
      user: {{ .Values.user }}
      password: {{ .Values.password }}

    # Serial settings
    serial:
      port: {{ .Values.addons.zigbee2mqtt.zigbee }}
{{- end }}