{{- if .Values.addons.zigbee2mqtt.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}-zigbee2mqtt
data:
  configuration.yaml: |
    homeassistant:
      enabled: {{ .Values.addons.zigbee2mqtt.homeassistant }}
      {{- if .Values.addons.zigbee2mqtt.homeassistant }}
      status: 'hass/status'
      {{- end }}

    frontend:
      enabled: true
      port: {{ .Values.addons.zigbee2mqtt.service.port }}

    permit_join: true

    advanced:
      homeassistant_legacy_entity_attributes: false
      homeassistant_legacy_triggers: false
      legacy_api: false
      legacy_availability_payload: false
    device_options:
      legacy: false

    mqtt:
      base_topic: zigbee2mqtt
      server: 'mqtt://{{ template "mosquitto.fullname" . }}'
      user: {{ .Values.authentification.user }}
      password: {{ .Values.authentification.password }}

    serial:
      port: {{ .Values.addons.zigbee2mqtt.port }}
      adapter: {{ .Values.addons.zigbee2mqtt.adapter }}
{{- end }}