{{- if .Values.addons.zigbee2mqtt.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto.fullname" . }}-zigbee2mqtt
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
    app.kubernetes.io/component: zigbee2mqtt
spec:
  replicas: {{ .Values.addons.zigbee2mqtt.replicaCount }}
  selector:
    matchLabels:
      {{- include "mosquitto.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zigbee2mqtt
  template:
    metadata:
      labels:
        {{- include "mosquitto.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zigbee2mqtt
    spec:
      serviceAccountName: {{ include "mosquitto.serviceAccountName" . }}
      initContainers:
        - name: init-volume
          image: busybox
          volumeMounts:
            - mountPath: /app/data
              name: data
            - mountPath: /tmp/configuration.yaml
              name: configmap
              subPath: configuration.yaml
          command:
            - sh
            - -c
            - >
              if [ ! -f /app/data/configuration.yaml ]; then
                cp /tmp/configuration.yaml /app/data/configuration.yaml;
              else
                echo "Le fichier /app/data/configuration.yaml existe déjà.";
              fi
      containers:
        - name: zigbee2mqtt
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            privileged: true
          image: "{{ .Values.addons.zigbee2mqtt.image.repository }}:{{ .Values.addons.zigbee2mqtt.image.tag }}"
          imagePullPolicy: {{ .Values.addons.zigbee2mqtt.image.pullPolicy }}
          ports:
            - name: "zigbee2mqtt"
              containerPort: {{ .Values.addons.zigbee2mqtt.service.port }}
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: zigbee2mqtt
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
          {{- with .Values.addons.zigbee2mqtt.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /app/data
              name: data
            - mountPath: {{ .Values.addons.zigbee2mqtt.port }}
              name: zigbee-usb
      volumes:
        - name: configmap
          configMap:
            name: {{ template "mosquitto.fullname" . }}-zigbee2mqtt
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}zigbee2mqtt-pvc-data{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: zigbee-usb
          hostPath:
            path: {{ .Values.addons.zigbee2mqtt.port }}
{{- end }}
