{{- if and .Values.addons.zigbee2mqtt.persistence.enabled (not .Values.addons.zigbee2mqtt.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zigbee2mqtt-pvc-data
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
    app.kubernetes.io/component: zigbee2mqtt
spec:
  accessModes:
    - {{ .Values.addons.zigbee2mqtt.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.addons.zigbee2mqtt.persistence.size | quote }}
  storageClassName: "{{ .Values.addons.zigbee2mqtt.persistence.storageClass }}"
{{- end }}
