{{- if .Values.addons.zigbee2mqtt.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto.fullname" . }}-zigbee2mqtt
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
    app.kubernetes.io/component: zigbee2mqtt
spec:
  replicas: {{ .Values.addons.zigbee2mqtt.replicaCount }}
  selector:
    matchLabels:
      {{- include "mosquitto.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zigbee2mqtt
  template:
    metadata:
      labels:
        {{- include "mosquitto.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zigbee2mqtt
    spec:
      serviceAccountName: {{ include "mosquitto.serviceAccountName" . }}
      securityContext:
        privileged: true
      containers:
        - name: zigbee2mqtt
          image: "{{ .Values.addons.zigbee2mqtt.image.repository }}:{{ .Values.addons.zigbee2mqtt.image.tag }}"
          imagePullPolicy: {{ .Values.addons.zigbee2mqtt.image.pullPolicy }}
          ports:
            - name: "main"
              containerPort: {{ .Values.addons.zigbee2mqtt.service.port }}
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
          volumeMounts:
            - mountPath: /app/data
              name: data
            - mountPath: /app/data/configuration.yaml
              subPath: configuration.yaml
            - name: usb-device
              mountPath: {{ .Values.addons.zigbee2mqtt.zigbee }}
          {{- with .Values.addons.zigbee2mqtt.resources }}
          resources:
            {{ . | nindent 12 }}
          {{- end }}
      volumes:
        - name: configmap
          configMap:
            name: {{ template "mosquitto.fullname" . }}-zigbee2mqtt
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}zigbee2mqtt-pvc-data{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: usb-device
          hostPath:
            path: {{ .Values.addons.zigbee2mqtt.zigbee }}
            type: CharDevice
{{- end }}