{{- if .Values.addons.zigbee2mqtt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mosquitto.fullname" . }}-zigbee2mqtt
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
    app.kubernetes.io/component: zigbee2mqtt
  {{- with .Values.service.loadBalancerIP }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ . }}
  {{- end }}
spec:
  type: {{ .Values.addons.zigbee2mqtt.service.type }}
  ports:
    - name: zigbee2mqtt
      port: {{ .Values.addons.zigbee2mqtt.service.port }}
      protocol: TCP
      targetPort: zigbee2mqtt
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zigbee2mqtt
{{- end }}
