{{- if .Values.rdtclient.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.fullname" . }}-rdtclient
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: rdtclient
spec:
  type: {{ .Values.rdtclient.service.type }}
  ports:
    - port: {{ .Values.rdtclient.service.port }}
      targetPort: rdtclient
      protocol: TCP
      name: rdtclient
  selector:
    {{- include "servarr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rdtclient
{{- end }}
