{{- if .Values.rdtclient.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servarr.fullname" . }}-rdtclient
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: rdtclient
spec:
  replicas: {{ .Values.rdtclient.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "servarr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rdtclient
  template:
    metadata:
      labels:
        {{- include "servarr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rdtclient
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ include "servarr.serviceAccountName" . }}
      containers:
        - name: rdtclient
          image: "{{ .Values.rdtclient.image.repository }}:{{ .Values.rdtclient.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{- range .Values.rdtclient.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: rdtclient
              containerPort: {{ .Values.rdtclient.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.rdtclient.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.rdtclient.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .| nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: rdtclient-config
              mountPath: /data/db
            {{- with .Values.rdtclient.data }}
            - name: rdtclient-data
              mountPath: {{ .path }}
            {{- end }}
      volumes:
        - name: rdtclient-config
          {{- if .Values.rdtclient.persistence.enabled }}
          persistentVolumeClaim:
            claimName: rdtclient-pvc-config
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.rdtclient.data }}
        - name: rdtclient-data
          hostPath: 
            path: {{ .hostPath }}
            type: Directory
          {{- end }}
      {{- with .Values.rdtclient.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rdtclient.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rdtclient.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
