{{- if .Values.rdtclient.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: {{ include "servarr.fullname" . }}-rdtclient
 annotations:
   cert-manager.io/cluster-issuer: "{{ .Values.rdtclient.ingress.tls }}"
spec:
 tls:
   - hosts:
       - {{ .Values.rdtclient.ingress.host }}
     secretName: tls-rdtclient
 rules:
   - host: {{ .Values.rdtclient.ingress.host }}
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: {{ include "servarr.fullname" . }}-rdtclient
               port:
                 name: rdtclient
{{- end }}