{{- $enabled := .Values.addons.redis.enabled }}
{{- $hasSecret := .Values.addons.redis.existingSecret }}
{{- $password := .Values.addons.redis.password | default "" }}

{{- if and $enabled (not $hasSecret) (ne $password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .name) }}-redis-secret
type: Opaque
data:
  password: {{ $password | b64enc }}
{{- end }}
