{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-nginx
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - name: "nginx"
      port: 80
      targetPort: "nginx"
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
