{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.fullname" . }}-nginx
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
        nginx/hash: {{ (printf "%.63s" (tpl (.Files.Get "files/default.conf.tpl") . | sha256sum)) }}
        nginx/hash: {{ (printf "%.63s" (tpl (.Files.Get "files/nginx.conf.tpl") . | sha256sum)) }}
    spec:
      # securityContext:
      #   fsGroup: 82
      containers:
      - env:
          - name: TZ
            value: "{{ .Values.timezone }}"
        image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}"
        name: nginx
        # securityContext:
        #   runAsUser: 82
        #   runAsGroup: 82
        ports:
          - containerPort: 80
            protocol: TCP
            name: "nginx"
        volumeMounts:
          {{- include "nextcloud.volumeMounts" . | trim | nindent 10 }}
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx
            subPath: default.conf
            readOnly: true
          - mountPath: /etc/nginx/nginx.conf
            name: nginx
            subPath: nginx.conf
            readOnly: true
      volumes:
      - name: nextcloud-data
        {{- if .Values.nextcloud.persistence.data.enabled }}
        hostPath:
          path: {{ .Values.nextcloud.persistence.data.hostPath }}
          type: Directory
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: nextcloud
        {{- if .Values.nextcloud.persistence.config.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.nextcloud.persistence.config.existingClaim }}{{ .Values.nextcloud.persistence.config.existingClaim }}{{- else }}nextcloud-config-pvc{{- end }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: nginx
        configMap:
            name: nginx
{{- end }}
