{{- if .Values.onlyoffice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-onlyoffice
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
spec:
  type: {{ .Values.onlyoffice.service.type }}
  ports:
    - name: "onlyoffice"
      port: 80
      targetPort: "onlyoffice"
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
{{- end }}
