{{- if .Values.authentification.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "esphome.fullname" . }}-esphome
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
type: Opaque
data:
  esphome-username: {{ .Values.username | b64enc | quote }}
  esphome-password: {{ .Values.password | b64enc | quote }}
{{- end }}