{{- if .Values.collabora.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.fullname" . }}-collabora
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: collabora
spec:
  replicas: {{ .Values.collabora.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: collabora
  template:
    metadata:
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: collabora
    spec:
      containers:
        - env:
            - name: DONT_GEN_SSL_CERT
              value: "1"
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: aliasgroup1
              value: "https://{{ .Values.nextcloud.host }}:443,https://collabora.{{ .Values.nextcloud.host }}:443"
            - name: dictionaries
              value: "{{ .Values.collabora.dictionaries }}"
            - name: extra_params
              value: --o:ssl.enable=false --o:ssl.termination=true --o:mount_jail_tree=false --o:logging.level=warning --o:home_mode.enable=true --o:security.seccomp=true --o:remote_font_config.url=https://{{ .Values.nextcloud.host }}/apps/richdocuments/settings/fonts.json
            - name: server_name
              value: "collabora.{{ .Values.nextcloud.host }}"
          image: "{{ .Values.collabora.repository }}:{{ .Values.collabora.tag }}"
          name: collabora
          ports:
            - containerPort: 9980
              protocol: TCP
              name: "collabora"
          securityContext:
            capabilities:
              add:
                - MKNOD
                - SYS_ADMIN
              drop:
                - NET_RAW
{{- end }}
