{{- if .Values.lidarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.fullname" . }}-lidarr
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: lidarr
spec:
  type: {{ .Values.lidarr.service.type }}
  ports:
    - port: {{ .Values.lidarr.service.port }}
      targetPort: lidarr
      protocol: TCP
      name: lidarr
  selector:
    {{- include "servarr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: lidarr
{{- end }}
