{{- if .Values.lidarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servarr.fullname" . }}-lidarr
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: lidarr
spec:
  replicas: {{ .Values.lidarr.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "servarr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: lidarr
  template:
    metadata:
      labels:
        {{- include "servarr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: lidarr
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ include "servarr.serviceAccountName" . }}
      {{- if .Values.postgresql.enabled }}
      initContainers:
        - name: check-db-ready
          image: bitnami/postgresql:16
          command: ['sh', '-c', 'until pg_isready -d lidarr_main -U lidarr -h {{ .Release.Name }}-cnpg-rw; do echo waiting for database; sleep 2; done;']
        - name: init-config
          image: busybox
          command: ['sh', '/tmp/init.sh']
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/config.xml
              subPath: config.xml
            - name: script-volume
              mountPath: /tmp/init.sh
              subPath: init.sh
            - name: lidarr-config
              mountPath: /config
      {{- end }}
      containers:
        - name: lidarr
          image: "{{ .Values.lidarr.image.repository }}:{{ .Values.lidarr.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: lidarr
              containerPort: {{ .Values.lidarr.port }}
              protocol: TCP
          env:
            {{- range .Values.lidarr.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.lidarr.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.lidarr.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            {{- with .Values.lidarr.data }}
            - name: lidarr-data
              mountPath: {{ .path }}
            {{- end }}
      volumes:
        - name: lidarr-config
          {{- if .Values.lidarr.persistence.enabled }}
          persistentVolumeClaim:
            claimName: lidarr-pvc-config
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.lidarr.data }}
        - name: lidarr-data
          hostPath: 
            path: {{ .hostPath }}
            type: Directory
        {{- end }}
        {{- if .Values.postgresql.enabled }}
        - name: config-volume
          configMap:
            name: config-lidarr
        - name: script-volume
          configMap:
            name: servarr-script
        {{- end }}
      {{- with .Values.lidarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lidarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lidarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
