whisper:
  enabled: false
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/faster-whisper
    tag: "2.0.0-gpu"
  env:
    - name: WHISPER_MODEL
      value: tiny-int8
    - name: WHISPER_BEAM
      value: 1
    - name: WHISPER_LANG
      value: fr
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: UMASK
      values: "022"
  persistence:
    enabled: true
    path: /config
    size: 1Gi
  port: 10300
  service:
    type: ClusterIP
    port: 10300
  ingress:
    enabled: false
    host: ""
    annotations: {}
  resources:
    limits:
      cpu: 1000m
      memory: 8000Mi
      nvidia.com/gpu: 0
    requests:
      cpu: 100m
      memory: 128Mi
      nvidia.com/gpu: 0
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

piper:
  enabled: false
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/piper
    tag: "1.4.0"
  env:
    - name: PIPER_VOICE
      value: en_US-lessac-medium
    - name: PIPER_LENGTH
      value: 1.0
    - name: PIPER_NOISE
      value: 0.667
    - name: PIPER_NOISEW
      value: 0.333
    - name: PIPER_SPEAKER
      value: 0
    - name: PIPER_PROCS
      value: 1
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
  persistence:
    enabled: true
    path: /config
    size: 1Gi
  port: 10300
  service:
    type: ClusterIP
    port: 10300
  ingress:
    enabled: false
    host: ""
    annotations: {}
  resources:
    limits:
      cpu: 1000m
      memory: 8000Mi
      nvidia.com/gpu: 0
    requests:
      cpu: 100m
      memory: 128Mi
      nvidia.com/gpu: 0
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

openwakeword:
  enabled: false
  replicaCount: 1
  image:
    repository:  rhasspy/wyoming-openwakeword
    tag: "1.10.0"
  extraArgs:
    - --preload-model
    - ok_nabu
    - --custom-model-dir
    - /custom
  port: 10400
  service:
    type: ClusterIP
    port: 10400
  ingress:
    enabled: false
    host: ""
    annotations: {}
  resources:
    limits:
      cpu: 1000m
      memory: 8000Mi
      nvidia.com/gpu: 0
    requests:
      cpu: 100m
      memory: 128Mi
      nvidia.com/gpu: 0

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
