{{- if .Values.httpd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-httpd
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: httpd
spec:
  type: {{ .Values.httpd.service.type }}
  ports:
    - name: "httpd-tcp"
      port: 8000
      targetPort: "httpd-tcp"
    - name: "httpd-udp"
      port: 8000
      targetPort: "httpd-udp"
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: httpd
{{- end }}
