{{- if .Values.flaresolverr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.fullname" . }}-flaresolverr
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: flaresolverr
spec:
  type: {{ .Values.flaresolverr.service.type }}
  ports:
    - port: {{ .Values.flaresolverr.service.port }}
      targetPort: flaresolverr
      protocol: TCP
      name: flaresolverr
  selector:
    {{- include "servarr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: flaresolverr
{{- end }}
