apiVersion: v1
kind: Service
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: nextcloud
spec:
  type: {{ .Values.nextcloud.service.type }}
  ports:
    - name: "http"
      port: {{ .Values.nextcloud.port }}
      targetPort: "http"
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nextcloud