apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-hooks
data:
  before-starting.sh: |-
    {{- tpl (.Files.Get "files/before-starting.sh.tpl") . | nindent 4 }}
  cron-script.sh: |-
    {{- .Values.nextcloud.job.script | nindent 4 }}