apiVersion: v1
data:
  username: {{ .Values.nextcloud.admin.user | b64enc }}
  password: {{ .Values.nextcloud.admin.password | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: kubernetes.io/basic-auth