{{- if .Values.facerecognition.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-facerecognition
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: facerecognition
spec:
  type: {{ .Values.facerecognition.service.type }}
  ports:
    - name: "facerecognition"
      port: 5000
      targetPort: "facerecognition"
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: facerecognition
{{- end }}
