{{- if .Values.recyclarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servarr.fullname" . }}-recyclarr
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: recyclarr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "servarr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: recyclarr
  template:
    metadata:
      labels:
        {{- include "servarr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: recyclarr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      serviceAccountName: {{ include "servarr.serviceAccountName" . }}
      containers:
        - name: recyclarr
          image: "{{ .Values.recyclarr.image.repository }}:{{ .Values.recyclarr.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{- range .Values.recyclarr.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: RECYCLARR_CREATE_CONFIG
              value: "true"
            - name: CRON_SCHEDULE
              value: {{ .Values.recyclarr.cron | quote }}
          resources:
            {{- toYaml .Values.recyclarr.resources | nindent 12 }}
          volumeMounts:
            - name: recyclarr-config
              mountPath: /config
      volumes:
        - name: recyclarr-config
          {{- if .Values.recyclarr.persistence.enabled }}
          persistentVolumeClaim:
            claimName: recyclarr-pvc-config
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.recyclarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.recyclarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.recyclarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
