{{- if .Values.addons.codeserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-assistant.fullname" . }}-codeserver
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: codeserver
spec:
  replicas: {{ .Values.addons.codeserver.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: codeserver
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: codeserver
    spec:
      serviceAccountName: {{ include "home-assistant.serviceAccountName" . }}
      securityContext:
        runAsUser: 0
      containers:
        - name: codeserver
          image: "{{ .Values.addons.codeserver.image }}:{{ .Values.addons.codeserver.tag }}"
          {{- if .Values.usbMount.enabled }}
          securityContext:
            privileged: true
          {{- end }}
          ports:
            - containerPort: {{ .Values.addons.codeserver.port }}
              name: codeserver
              protocol: TCP
          env:
            {{- range .Values.addons.codeserver.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: PUID
            {{- if .Values.usbMount.enabled }} 
              value: "0"
            {{- else }}
              value: "1000"
            {{- end }}
          {{- with .Values.addons.codeserver.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.addons.codeserver.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /config
              name: codeserver-config
            {{- if .Values.persistence.enabled }}
            - name: home-assistant-config
              mountPath: /config/workspace
            {{- end }}
          {{- with .Values.addons.codeserver.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: codeserver-config
          {{- if .Values.addons.codeserver.persistence.enabled }}
          persistentVolumeClaim:
            claimName: codeserver-pvc-config
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: {{ template "home-assistant.fullname" . }}-pvc-config
        {{- end }}
{{- end }}
