{{- if .Values.addons.codeserver.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "home-assistant.fullname" . }}-codeserver
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.addons.codeserver.ingress.host }}`)
    kind: Rule
    services:
    - name: {{ template "home-assistant.fullname" . }}-codeserver
      port: {{ .Values.addons.codeserver.service.port }}
{{- end }}