apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config-script
data:
  init.sh: |
    #!/bin/sh
    set -e

    SCENES="/config/scenes.yaml"
    SECRETS="/config/secrets.yaml"
    SCRIPTS="/config/scripts.yaml"
    CONFIG="/config/configuration.yaml"
    AUTOMATIONS="/config/automations.yaml"
    LOG="/config/home-assistant.log"

    echo "Début de la configuration de Home Assistant .."
    cp /config-init/configuration.yaml $CONFIG
    echo "[]" > $AUTOMATIONS
    touch $SCENES
    touch $SCRIPTS
    touch $SECRETS
    echo "Mise à jour du fichier de configuration de Home Assistant"


    echo "Fin de la configuration de Home Assistant .."
