apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config-init
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    recorder:
      purge_keep_days: 30
      db_url: postgresql://{{.Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-cnpg-rw:5432/{{ .Release.Name }}?client_encoding=utf8

    {{- if .Values.ingress.enabled }}
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 127.0.0.1
    {{- end}}

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml