{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "home-assistant.fullname" . }}-codeserver
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: codeserver-certificat-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "home-assistant.fullname" . }}-codeserver
            port:
              number: {{ .Values.service.port }}
{{- end }}