apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config-script
data:
  init.sh: |
    #!/bin/sh
    set -e

    SCENES="/config/scenes.yaml"
    SECRETS="/config/secrets.yaml"
    SCRIPTS="/config/scripts.yaml"
    CONFIG="/config/configuration.yaml"
    AUTOMATIONS="/config/automations.yaml"
    LOG="/config/home-assistant.log"

    echo "Début de la configuration de Home Assistant .."

    if [ ! -f "$CONFIG" ]; then
      cp /config-init/configuration.yaml $CONFIG
    fi
    if [ ! -f "$AUTOMATIONS" ]; then
      echo "[]" > $AUTOMATIONS
    fi
    if [ ! -f "$SCENES" ]; then
      touch $SCENES
    fi
    if [ ! -f "$SCRIPTS" ]; then
      touch $SCRIPTS
    fi
    if [ ! -f "$SECRETS" ]; then
      touch $SECRETS
    fi

    chown 1000:1000 -R /config

    echo "Mise à jour du fichier de configuration de Home Assistant"
    echo "Fin de la configuration de Home Assistant .."
