replicaCount: 1

image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  tag: "2025.9.0"

timezone: "Europe/Paris"

usbMount:
  enabled: false
  path: /dev/ttyACM0

service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: false
  host: ""
  annotations: {}

serviceAccount:
  create: false
  automount: false

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
  existingClaim: false
  storageClass: ""

postStart:
  command: ""

livenessProbe:
  httpGet:
    path: /
    port: 8123
  initialDelaySeconds: 60
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: 8123
  initialDelaySeconds: 30
  periodSeconds: 15

postgresql:
  enabled: false
  storageClass: openebs-zfsdb
  auth:
    username: admin
    password: changeme
    database: home-assistant

addons:
  #################
  # Coder addon   #
  #################
  codeserver:
    replicaCount: 1
    enabled: false
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 1Gi
      existingClaim: false
      storageClass: ""
    image: lscr.io/linuxserver/code-server
    tag: "4.92.2"
    ingress:
      enabled: false
      annotations: {}
      host: ""
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1"
    env:
    - name: UMASK
      values: "000"
    port: 8443
    service:
      type: ClusterIP
      port: 8443


