apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  custom.css: |
{{- .Values.config.custom.css | nindent 4 }}
  custom.js: |
{{- .Values.config.custom.js | nindent 4 }}
  bookmarks.yaml: |
{{- .Values.config.bookmarks | nindent 4 }}
  docker.yaml: |
{{- .Values.config.docker | nindent 4 }}
  kubernetes.yaml: |
{{- .Values.config.kubernetes | nindent 4 }}
  services.yaml: |
{{- .Values.config.services | nindent 4 }}
  settings.yaml: |
{{- .Values.config.settings | nindent 4 }}
  widgets.yaml: |
{{- .Values.config.widgets | nindent 4 }}