{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "homepage.serviceAccountName" . }}
{{- end }}
