{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
secrets:
  - name: homepage
{{- end }}
