replicaCount: 1

timezone: "Europe/Paris"

image:
  repository: vaultwarden/server
  tag: "1.32.7-alpine"

ingress:
  enabled: false
  host: ""
  annotations: {}
  
service:
  type: ClusterIP

postgresql:
  enabled: false
  storageClass: ""
  user: vaultwarden
  password: changeme

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  existingClaim: false
  storageClass: ""