{{- if .Values.imaginary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-imaginary
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: imaginary
spec:
  type: {{ .Values.imaginary.service.type }}
  ports:
    - name: "imaginary"
      port: 9000
      targetPort: "imaginary"
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: imaginary
{{- end }}
