{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "frigate.fullname" . }}-config
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  storageClassName: "{{ .Values.persistence.config.storageClass }}"
{{- end }}
{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "frigate.fullname" . }}-data
  {{- if .Values.persistence.data.skipuninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  storageClassName: "{{ .Values.persistence.data.storageClass }}"
{{- end }}