apiVersion: v1
kind: Service
metadata:
  name: {{ template "frigate.fullname" . }}
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
    - name: rtmp
      port: 1935
      protocol: TCP
      targetPort: rtmp
    - name: http-auth
      port: 8971
      protocol: TCP
      targetPort: http-auth
    - name: rtsp
      port: 8554
      protocol: TCP
      targetPort: rtsp
    - name: webrtc-tcp
      port: 8555
      protocol: TCP
      targetPort: webrtc-tcp
    - name: webrtc-udp
      port: 8555
      protocol: UDP
      targetPort: webrtc-udp
  selector:
    {{- include "frigate.selectorLabels" . | nindent 4 }}
