replicaCount: 1

image:
  repository: ghcr.io/esphome/esphome
  pullPolicy: IfNotPresent
  tag: "2024.12.2"

username: admin
password: changeme

serviceAccount:
  create: false

timezone: "Europe/Paris"

service:
  type: ClusterIP
  port: 6052

ingress:
  enabled: false

livenessProbe:
  httpGet:
    path: /
    port: 6052
readinessProbe:
  httpGet:
    path: /
    port: 6052


persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  existingClaim: false
  storageClass: ""
