replicaCount: 1

image:
  repository: esphome/esphome
  pullPolicy: IfNotPresent
  tag: "2025.2.2"

username: admin
password: changeme

serviceAccount:
  create: false

timezone: "Europe/Paris"

service:
  type: ClusterIP
  port: 6052

ingress:
  enabled: false
  host: ""
  annotations: {}

livenessProbe:
  httpGet:
    path: /
    port: 6052
readinessProbe:
  httpGet:
    path: /
    port: 6052

resources: {}
  # requests:
  #   memory: 500Mi
  #   cpu: 500m
  # limits:
  #   memory: 500Mi
  #   cpu: 200m

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  existingClaim: false
  storageClass: ""
