{{- if .Values.byparr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.fullname" . }}-byparr
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: byparr
spec:
  type: {{ .Values.byparr.service.type }}
  ports:
    - port: {{ .Values.byparr.service.port }}
      targetPort: byparr
      protocol: TCP
      name: byparr
  selector:
    {{- include "servarr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: byparr
{{- end }}
